name: Deploy Website

# Trigger workflow on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Node.js (if your website uses JS)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3. Install dependencies (optional)
      - name: Install dependencies
        run: npm install
        working-directory: ./your-website-folder  # adjust if your site is in a subfolder

      # 4. Build website (optional, e.g., for React/Vue)
      - name: Build
        run: npm run build
        working-directory: ./your-website-folder

      # 5. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./your-website-folder/build  # change according to your build folder
